name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the Python version you need

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements.txt file

      - name: Install and Build
        run: |
          npm install -g mermaid.cli
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
